services:
  netip:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - ./data:/data
      - ./config:/config:ro
      - ./web/dist:/web/dist:ro
    cap_add:
      - NET_RAW
    healthcheck:
      test: ["CMD", "/bin/netip", "-v"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
